### 用户服务
GET localhost:9090/users/awifi


### zuul-basic
GET localhost:8088/users-service/users/awifi
deviceId: 123

### zuul-path
GET localhost:8088/users/awifi

### zuul-serviceId
GET localhost:8088/users-service/users/awifi

###

