### 用户服务
GET 127.0.0.1:9099/users/awifi


### zuul-basic
GET 127.0.0.1:8088/users-service/users/awifi
deviceId: 123
Authorization: 456

### zuul-path
GET 127.0.0.1:8088/myusers/users/awifi
deviceId: 123
Authorization: 456

### zuul-serviceId
GET 127.0.0.1:8088/users-service/users/awifi

###

