server:
  port: 8088
spring:
  application:
    name: zuulZ-example
  cloud:
    consul:
      host: 192.168.212.14
      discovery:
        health-check-critical-timeout: 10s
  http:
    multipart:
      file-size-threshold: 10MB # 设置这个的目的是在文件上传的时候，会不断的将请求中的文件数据写入磁盘，如果不设置，所有的二进制数据就会存放在内存中，通过Zuul做请求转发的时候，相当于会把这个数据给复制两份到内存中，很容易撑爆系统内存，造成OOM。
      max-file-size: 200MB
      max-request-size: 200MB
      location:
  jackson:
    default-property-inclusion: non_null
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 240000 # (ConnectTimeout + ReadTimeout) *2
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  sensitive-headers: Cookie,Set-Cookie,Authorization # 全局黑名单功能，声明的才是需要拦截的
  routes:
    users-service:
      path: /myusers/**
      serviceId: users-service
      sensitiveHeaders: Cookie,Set-Cookie            # 局部黑名单功能，声明的才是需要拦截的

# 禁用 Zuul 过滤器
#zuul.LogFilter.pre.disable: true


